name: CI Workflow - Multi-Modules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y tar  # Installez tar si nÃ©cessaire

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 globally
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.13-11/x64
          PATH: $JAVA_HOME/bin:$PATH

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install frontend dependencies
        working-directory: ./front
        run: npm install

      - name: Run frontend tests and generate coverage report
        working-directory: ./front
        run: npm test -- --coverage

      - name: Build backend
        working-directory: ./back
        run: mvn clean install

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME/sonar-scanner
          echo "$HOME/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH

      - name: Run SonarCloud Scan for Multi-Module Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.13-11/x64
          PATH: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.13-11/x64/bin:$PATH
        run: |
          $HOME/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner -X
